version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    # https://github.com/facebook/create-react-app/issues/8688
    # https://stackoverflow.com/questions/60790696/react-scripts-start-exiting-in-docker-foreground-cmd
    stdin_open: true
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Don't let Jest watch the files, exit on completion.
    command: ["npm", "run", "test", " --forceExit"]
    volumes:
      - /app/node_modules
      - .:/app