FROM node:alpine

WORKDIR /app

COPY package.json .

RUN npm install

# We could remove this since we are using
# Docker Volumes, but it's good to keep it around
# as a reference in the future.
COPY . .

CMD ["npm", "run", "start"]

# docker build -f Dockerfile.dev .
# docker run -p 3000:3000 <id|tag>
# Using Docker Volumes:
# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app <id|tag>
# first -v is the bookmark.
# second -v is mapping the pwd to the /app folder.